[project]
name = "pulse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.121.2",
    "jinja2>=3.1.6",
    "matplotlib>=3.10.7",
    "python-multipart>=0.0.20",
    "uvicorn[standard]>=0.38.0",
]
